In [1]:
import pandas as pd

## Explore drug response data

In [2]:
fitted = pd.read_excel("D:\CancerRx\data\GDSC2_fitted_dose_response_27Oct23.xlsx")

<>:1: SyntaxWarning: "\C" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\C"? A raw string is also an option.
<>:1: SyntaxWarning: "\C" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\C"? A raw string is also an option.
C:\Users\muska\AppData\Local\Temp\ipykernel_29440\2829022393.py:1: SyntaxWarning: "\C" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\C"? A raw string is also an option.
  fitted = pd.read_excel("D:\CancerRx\data\GDSC2_fitted_dose_response_27Oct23.xlsx")

In [3]:
fitted.head()

,DATASET,NLME_RESULT_ID,NLME_CURVE_ID,CELL_LINE_NAME,SANGER_MODEL_ID,CANCER_TYPE,DRUG_ID,DRUG_NAME,PUTATIVE_TARGET,PATHWAY_NAME,MIN_CONC,MAX_CONC,LN_IC50,AUC,RMSE,Z_SCORE
0,GDSC2,343,15946310,PFSK-1,SIDM01132,Other Solid Cancers,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-1.463887,0.930220,0.089052,0.433123
1,GDSC2,343,15946548,A673,SIDM00848,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-4.869455,0.614970,0.111351,-1.421100
2,GDSC2,343,15946830,ES5,SIDM00263,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-3.360586,0.791072,0.142855,-0.599569
3,GDSC2,343,15947087,ES7,SIDM00269,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-5.044940,0.592660,0.135539,-1.516647
4,GDSC2,343,15947369,EW-11,SIDM00203,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-3.741991,0.734047,0.128059,-0.807232

In [4]:
fitted['LN_IC50'].describe()

count    242036.000000
mean          2.817079
std           2.762229
min          -8.747724
25%           1.508018
50%           3.236731
75%           4.700110
max          13.820189
Name: LN_IC50, dtype: float64

## RNASeq Data

In [ ]:
rsem_expected_count = pd.read_csv("D:\CancerRx\data\\rnaseq_merged_rsem_expected_count_20260323.csv")
rsem_fpkm = pd.read_csv("D:\CancerRx\data\\rnaseq_merged_rsem_fpkm_20260323.csv")
rsem_tpm = pd.read_csv("D:\CancerRx\data\\rnaseq_merged_rsem_tpm_20260323.csv")
# merged = pd.read_csv("D:\CancerRx\data\\rnaseq_merged_20260323.csv")

In [7]:
rsem_expected_count.head(10)

,model_id,Unnamed: 1,Unnamed: 2,SIDM00001,SIDM00002,SIDM00003,SIDM00005,SIDM00006,SIDM00007,SIDM00008,...,SIDM02262,SIDM02263,SIDM02264,SIDM02265,SIDM02266,SIDM02267,SIDM02268,SIDM02269,SIDM02270,SIDM02271
0,model_name,NaN,NaN,MEC-1,NBsusSR,M14,MDA-MB-134-VI,MCC26,MCC13,MCAS,...,WTSI-COLO_427,WTSI-COLO_425,WTSI-COLO_061,WTSI-COLIVM_100,WTSI-COLIVM_093,WTSI-COLIVM_092,WTSI-COLO_452,WTSI-PANC_131,WTSI-COLIVM_068,WTSI-GAST_200
1,data_source,NaN,NaN,Broad,Sanger,Sanger,Broad,Sanger,Sanger,Broad,...,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger
2,gene_symbol,ensembl_gene_id,gene_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A1BG,ENSG00000121410,SIDG00001,207.14,860.26,795.66,621.89,657.29,3502.61,1.76,...,4,12.09,2,8.15,49.19,177.09,55.28,0,7.35,0
4,A1BG-AS1,ENSG00000268895,SIDG00002,219.85,757.1,1825.95,552.86,999.35,2290.38,5.47,...,0,0,2,6.43,7.12,45.21,17.43,35.3,17.85,0
5,A1CF,ENSG00000148584,SIDG00003,1,17,4,1,33.17,7,5,...,389,141,24,759,513,584,664,0,881.98,5
6,A2M,ENSG00000175899,SIDG00004,44,228.93,11427.07,44,29573.36,28,7,...,19,0,4,9,6,0,12,47,93,34
7,A2M-AS1,ENSG00000245105,SIDG00005,0,72,124.93,157,146.64,213,2,...,25,0,8,5,2,8,18,47,29,26
8,A2ML1,ENSG00000166535,SIDG00006,0,157,1,4,14,3,38,...,0,7,47,6,27,0,5,0,4,0
9,A2ML1-AS1,ENSG00000256661,SIDG00007,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
rsem_fpkm.head(10)

,model_id,Unnamed: 1,Unnamed: 2,SIDM00002,SIDM00003,SIDM00006,SIDM00007,SIDM00009,SIDM00014,SIDM00018,...,SIDM02262,SIDM02263,SIDM02264,SIDM02265,SIDM02266,SIDM02267,SIDM02268,SIDM02269,SIDM02270,SIDM02271
0,model_name,NaN,NaN,NBsusSR,M14,MCC26,MCC13,MC-1010,LIM1215,K052,...,WTSI-COLO_427,WTSI-COLO_425,WTSI-COLO_061,WTSI-COLIVM_100,WTSI-COLIVM_093,WTSI-COLIVM_092,WTSI-COLO_452,WTSI-PANC_131,WTSI-COLIVM_068,WTSI-GAST_200
1,data_source,NaN,NaN,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,...,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger
2,gene_symbol,ensembl_gene_id,gene_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A1BG,ENSG00000121410,SIDG00001,15.27,10.14,8.85,48.15,17.59,0.06,15.63,...,0.22,1.25,0.23,0.16,0.42,18.84,8.35,0,0.05,0
4,A1BG-AS1,ENSG00000268895,SIDG00002,2.97,5.39,3.15,7.43,6.3,0.15,4.47,...,0,0,0.15,0.08,0.15,0.72,0.32,1.07,0.18,0
5,A1CF,ENSG00000148584,SIDG00003,0.01,0.01,0.02,0.01,0.01,0.51,0,...,2.59,2.01,0.21,4.08,1.83,4.94,3.74,0,3.03,0.01
6,A2M,ENSG00000175899,SIDG00004,0.34,11.4,31.26,0.05,0.05,0.06,0.31,...,0.07,0,0.08,0.05,0.05,0,0.24,0.33,0.34,0.16
7,A2M-AS1,ENSG00000245105,SIDG00005,0.19,0.23,0.3,0.41,0.02,0.11,0.27,...,0.2,0,0.13,0.05,0.02,0.07,0.26,0.72,0.23,0.32
8,A2ML1,ENSG00000166535,SIDG00006,0.27,0,0.07,0,0.02,0,4.62,...,0,0.06,0.35,0.07,0.17,0,0.04,0,0.01,0
9,A2ML1-AS1,ENSG00000256661,SIDG00007,0,0,0,0,0,0,0.07,...,0,0,0,0,0,0,0,0,0,0

In [9]:
rsem_tpm.head(10)

,model_id,Unnamed: 1,Unnamed: 2,SIDM00001,SIDM00002,SIDM00003,SIDM00005,SIDM00006,SIDM00007,SIDM00008,...,SIDM02262,SIDM02263,SIDM02264,SIDM02265,SIDM02266,SIDM02267,SIDM02268,SIDM02269,SIDM02270,SIDM02271
0,model_name,NaN,NaN,MEC-1,NBsusSR,M14,MDA-MB-134-VI,MCC26,MCC13,MCAS,...,WTSI-COLO_427,WTSI-COLO_425,WTSI-COLO_061,WTSI-COLIVM_100,WTSI-COLIVM_093,WTSI-COLIVM_092,WTSI-COLO_452,WTSI-PANC_131,WTSI-COLIVM_068,WTSI-GAST_200
1,data_source,NaN,NaN,Broad,Sanger,Sanger,Broad,Sanger,Sanger,Broad,...,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger
2,gene_symbol,ensembl_gene_id,gene_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A1BG,ENSG00000121410,SIDG00001,3.853,4.5059,3.9736,5.7038,3.9069,6.1198,0.0566,...,0.1635,0.848,0.2869,0.189,0.5361,3.5583,2.9635,0,0.0976,0
4,A1BG-AS1,ENSG00000268895,SIDG00002,1.8156,2.3868,3.1408,3.3334,2.5801,3.5336,0.0976,...,0,0,0.189,0.0976,0.2141,0.4957,0.3334,0.8953,0.2869,0
5,A1CF,ENSG00000148584,SIDG00003,0,0.0286,0.0144,0.0566,0.0426,0.0144,0.0426,...,1.281,1.1953,0.263,2.2265,1.5753,1.9336,2.0144,0,2.2079,0.0144
6,A2M,ENSG00000175899,SIDG00004,0.2388,0.5753,4.1326,0.5261,5.6562,0.0976,0.0976,...,0.0566,0,0.111,0.0566,0.0841,0,0.263,0.3448,0.4854,0.2141
7,A2M-AS1,ENSG00000245105,SIDG00005,0,0.3448,0.4114,1.4489,0.5656,0.6599,0.0286,...,0.1506,0,0.1635,0.0566,0.0286,0.0566,0.275,0.6599,0.3448,0.3896
8,A2ML1,ENSG00000166535,SIDG00006,0,0.4751,0,0.4114,0.1506,0.0144,0.2265,...,0,0.0566,0.4114,0.0841,0.2388,0,0.0566,0,0.0286,0
9,A2ML1-AS1,ENSG00000256661,SIDG00007,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
merged.head(10)

,model_name,model_id,gene_symbol,ensembl_gene_id,gene_id,htseq_read_count,rsem_expected_count,rsem_fpkm,rsem_tpm,htseq_fpkm,data_source
0,LS-123,SIDM00776,DVL2,ENSG00000004975,SIDG07167,NaN,1021.0,NaN,3.5521,NaN,Broad
1,MOLM-13,SIDM00437,STPG1,ENSG00000001460,SIDG36759,NaN,442.0,NaN,2.2898,NaN,Broad
2,HARA,SIDM00598,STPG1,ENSG00000001460,SIDG36759,NaN,517.0,NaN,2.9486,NaN,Broad
3,HCC-366,SIDM01070,STPG1,ENSG00000001460,SIDG36759,NaN,427.0,NaN,2.4906,NaN,Broad
4,HKGZ-CC,SIDM01819,STPG1,ENSG00000001460,SIDG36759,NaN,2089.0,NaN,1.6369,NaN,Broad
5,SKNO-1,SIDM01864,STPG1,ENSG00000001460,SIDG36759,NaN,141.0,NaN,1.0072,NaN,Broad
6,SLR21,SIDM01862,STPG1,ENSG00000001460,SIDG36759,NaN,606.0,NaN,2.4087,NaN,Broad
7,Hs-751-T,SIDM01700,STPG1,ENSG00000001460,SIDG36759,NaN,1025.0,NaN,3.5644,NaN,Broad
8,C84,SIDM01548,STPG1,ENSG00000001460,SIDG36759,NaN,524.0,NaN,2.0000,NaN,Broad
9,TM-31,SIDM01460,STPG1,ENSG00000001460,SIDG36759,NaN,2236.0,NaN,4.3653,NaN,Broad

## Understanding of what the data represents
### Drug response
- ln_ic50 represents the log of concentration where drug kills 50% of cells. lower is better.
- auc represents overall drug response. high auc means that the cells may not die after a point of high dosage also

### RNASeq data
Basically there are some issues with raw data:
- Some genes are long so there is a chance you may find shorter genes more
- some cell lines are sequenced more deeply (more reads - more chunks) which leads to higher probability of finding some genes
#### what is in the files
- merged -> for every cell line x gene the expected raw count, the tpm, the fpkm 
- expected count -> the raw counts of the times a gene was seen in the cell line
- fpkm -> fragments per kilobase per million -> essentially normalizes for gene length and sequencing depth. but for every CLxGene pair we can't do 1to1 comparison because genes have different lengths and depths are different
- tpm -> transcripts per million -> divides by gene length and then makes sure that for every column (cell line) we can do 1to1 comparisons, makes sure all gene normalized counts are normalized so the cell lne count sums to 1 million

## Understanding of what the data represents
### Drug response
- ln_ic50 represents the log of concentration where drug kills 50% of cells. lower is better.
- auc represents overall drug response. high auc means that the cells may not die after a point of high dosage also

### RNASeq data
Basically there are some issues with raw data:
- Some genes are long so there is a chance you may find shorter genes more
- some cell lines are sequenced more deeply (more reads - more chunks) which leads to higher probability of finding some genes
#### what is in the files
- merged -> for every cell line x gene the expected raw count, the tpm, the fpkm 
- expected count -> the raw counts of the times a gene was seen in the cell line
- fpkm -> fragments per kilobase per million -> essentially normalizes for gene length and sequencing depth. but for every CLxGene pair we can't do 1to1 comparison because genes have different lengths and depths are different
- tpm -> transcripts per million -> divides by gene length and then makes sure that for every column (cell line) we can do 1to1 comparisons, makes sure all gene normalized counts are normalized so the cell lne count sums to 1 million

## Generate relevant data

In [12]:
drugs_chosen =  ['Erlotinib', 'Gefitinib', 'Tamoxifen', 'Paclitaxel', 'Gemcitabine']

In [21]:
tpm_transpose = rsem_tpm.transpose()

In [22]:
tpm_transpose.columns = tpm_transpose.iloc[0]
tpm_transpose=tpm_transpose[3::]

In [23]:
fitted.head()

,DATASET,NLME_RESULT_ID,NLME_CURVE_ID,CELL_LINE_NAME,SANGER_MODEL_ID,CANCER_TYPE,DRUG_ID,DRUG_NAME,PUTATIVE_TARGET,PATHWAY_NAME,MIN_CONC,MAX_CONC,LN_IC50,AUC,RMSE,Z_SCORE
0,GDSC2,343,15946310,PFSK-1,SIDM01132,Other Solid Cancers,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-1.463887,0.930220,0.089052,0.433123
1,GDSC2,343,15946548,A673,SIDM00848,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-4.869455,0.614970,0.111351,-1.421100
2,GDSC2,343,15946830,ES5,SIDM00263,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-3.360586,0.791072,0.142855,-0.599569
3,GDSC2,343,15947087,ES7,SIDM00269,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-5.044940,0.592660,0.135539,-1.516647
4,GDSC2,343,15947369,EW-11,SIDM00203,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.0001,0.1,-3.741991,0.734047,0.128059,-0.807232

In [24]:
tpm_transpose.index.name = 'model_id'
tpm_transpose = tpm_transpose.reset_index()

In [25]:
tpm_transpose.head()

model_id,model_id,model_name,data_source,gene_symbol,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
0,SIDM00001,MEC-1,Broad,NaN,3.853,1.8156,0,0.2388,0,0,...,0.7655,1.9561,2.8992,0.8953,0.0,1.926,4.1562,NaN,3.0959,3.6792
1,SIDM00002,NBsusSR,Sanger,NaN,4.5059,2.3868,0.0286,0.5753,0.3448,0.4751,...,1.7137,2.6803,5.6156,0.848,0.0,3.7388,5.2687,0.0,4.3519,5.4182
2,SIDM00003,M14,Sanger,NaN,3.9736,3.1408,0.0144,4.1326,0.4114,0,...,1.0909,2.101,4.0488,2.6369,0.0976,3.7148,6.959,0.0,4.3561,5.5622
3,SIDM00005,MDA-MB-134-VI,Broad,NaN,5.7038,3.3334,0.0566,0.5261,1.4489,0.4114,...,1.7093,2.257,4.3111,1.0909,0.0,2.4463,4.0009,NaN,3.3813,4.2434
4,SIDM00006,MCC26,Sanger,NaN,3.9069,2.5801,0.0426,5.6562,0.5656,0.1506,...,1.4005,2.3533,3.9551,2.98,0.0,3.6334,8.5417,0.0,3.5211,5.1839

In [26]:
filtered_drugs = fitted[fitted['DRUG_NAME'].isin(drugs_chosen)]

In [27]:
drugs_response_tpm_merged_data = pd.merge(
    left = tpm_transpose,
    right=filtered_drugs,
    left_on='model_id',
    right_on="SANGER_MODEL_ID")

In [28]:
drugs_response_tpm_merged_data.shape

(4663, 41165)

In [37]:
drugs_response_tpm_merged_data['DRUG_NAME'].value_counts()

DRUG_NAME
Gemcitabine    935
Gefitinib      933
Paclitaxel     933
Tamoxifen      932
Erlotinib      930
Name: count, dtype: int64

In [ ]:
drugs_response_tpm_merged_data.to_csv("../data/required_data.csv")